Scala 2.13 upgrade
hmrc/amls pull request #341
Opened 2023-03-31 11:41 UTC by Michael-RJ

[Your pull request description here]

## Related / Dependant PRs?

## How Has This Been Tested?

## Checklist

- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [ ] Build passing.
- [ ] Unit tests have full coverage.
- [ ] Unit test approach and implementation has been reviewed with QA (testers).
- [ ] Requires acceptance test run.
- [ ] Appropriate labels added.
- [ ] RELEASE NOTES ADDED.

2023-07-13 10:54 UTC, lewishay requested changes

2023-07-13 10:54 UTC, lewishay commented on project/AppDependencies.scala
> +    "uk.gov.hmrc.mongo"    %% "hmrc-mongo-play-28"         % "0.74.0",
Is there a reason why mongo dependency wasn't updated? It would be nice to do it here but I am conscious of the size of the PR already. Is it worth trying the upgrade in hopes that it's a simple version bump, and then if there are numerous things that need fixing then split it out into another ticket?

2023-07-13 10:54 UTC, lewishay commented on project/AppDependencies.scala
> +  val bootstrapVersion = "7.15.0"
This can be bumped to 7.19.0 now

2023-07-13 10:54 UTC, lewishay commented on project/AppDependencies.scala
> +        "uk.gov.hmrc"             %% "bootstrap-test-play-28"    % bootstrapVersion         % scope,
By adding bootstrap-test-play we get a bunch of these libraries for free as transitive dependencies. There are also a few here that just look unnecessary to me. Could you try removing the following:
- scalatest
- scalatestplus-play
- scalacheck (just the standard one, but keep 1-17)
- pegdown
- play-test

There are more here we could eventually remove too but it looks like at the moment there's a few version conflicts between what we have here and bootstrap that would need code changes, so we can leave those for now.

2023-07-13 10:54 UTC, lewishay commented on project/AppDependencies.scala
> +        "uk.gov.hmrc.mongo"       %% "hmrc-mongo-test-play-28" % "0.74.0"                 % scope,
Most of these deps are unnecessary for IT scope considering all we have are a few repository specs. I think all you will need is bootstrap and mongo - I checked it on my machine and seemed to pass fine, but let me know if any issues on your side.

2023-07-13 10:54 UTC, lewishay commented on test/connectors/ViewDESConnectorSpec.scala
> +//    "return a failed future" in new Fixture {
Can you uncomment these tests 😄

2023-07-14 14:29 UTC, Michael-RJ commented on project/AppDependencies.scala
> +    "uk.gov.hmrc.mongo"    %% "hmrc-mongo-play-28"         % "0.74.0",
Raise new ticket for mongo upgrade.

2023-07-14 14:29 UTC, Michael-RJ commented on project/AppDependencies.scala
> +  val bootstrapVersion = "7.15.0"
Done.

2023-07-14 14:29 UTC, Michael-RJ commented on project/AppDependencies.scala
> +        "uk.gov.hmrc"             %% "bootstrap-test-play-28"    % bootstrapVersion         % scope,
Done.

2023-07-14 14:29 UTC, Michael-RJ commented on test/connectors/ViewDESConnectorSpec.scala
> +//    "return a failed future" in new Fixture {
Done.

2023-07-14 15:40 UTC, lewishay submitted a review, later dismissed

2023-07-19 09:05 UTC, lewishay approved these changes

2023-07-19 09:06 UTC, merged